apiVersion: v1
kind: Service
metadata:
  name: noizy-frontend
  namespace: noizy
spec:
  selector:
    app: noizy-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
